### PR TITLE
add changes for lora adapter support and /v1/models endpoint

### PR DESCRIPTION
**Pull request by sven-knoblauch**
small changes to add the lora modules ENV variable (supporting 1 lora adapter) as solution for #119 
with the format:  `{"name": "xxx", "path": "xxx/xxxxx", "base_model_name": "xxx/xxxx"}`

also change of the v1/models endpoint to return all models

### CODE REVIEW

**Comment by pandyamarut** [comment]
Thanks for the PR. @sven-knoblauch . Can you please also add how did you test the PR?

**Comment by sven-knoblauch** [comment]
I made a docker container with the given Dockerfile (on dockerhub: svenknob/runpod-vllm-worker) and tested it on runpod serverless. Worked with a custom trained lora adapter (added in the runpod GUI as ENV variable: LORA_MODULES) with an awq mistral model. The lora adapter is also visible in the v1/models endpoint.

**Comment by nielsrolf** [comment]
Is a docker image publicly available that contains this PR?

**Comment by sven-knoblauch** [comment]
Added a pull request for changing the readme #130.
Usage is similar to the usage in the "original" vllm server. The env var name is LORA_MODULES and the format is {"name": "xxx", "path": "xxx/xxxx", "base_model_name": "xxx/xxxx"}, where the name is the name the http requests are made for, the path is the huggingface path of the adapter and the base_model_name is the modelname it is trained on.

For now you can use my docker image svenknob/runpod-vllm-worker, till it has been published.

**Pull request merged**
